spring.application.name=Finance

spring.datasource.url = jdbc:mysql://localhost:3306/finance
spring.datasource.username = root
spring.datasource.password = aditya@123

spring.jpa.hibernate.ddl-auto=update
spring.datasource.show-sql=true
spring.jpa.defer-datasource-initialization=true
